version: '3'
services:
  server:
    container_name: telegram_bot1  # 自定義容器名稱
    restart: always # 跟系統服務一起重啟
    network_mode: host # 網路: 使用實體機
    # 編譯時的設置
    build: 
      context: .
      dockerfile: Dockerfile.env
    